; ==============================================================================
; SYSTEM VARIABLES
; ==============================================================================
            
;--- KEYBOARD RELATED VARIABLES ------------------------------------------------

KBDVAL      DS.B    1
KBDEDGE     DS.B    1

;--- TIMED INTERRUPT RELATED VARIABLES -----------------------------------------

CURRFPS     DS.W    1
SCRINTCT    DS.B    1
            DS.W    0





*~Font name~Fixedsys~
*~Font size~9~
*~Tab type~1~
*~Tab size~4~
